import type { TargetRoleInfo, ProjectTemplate } from '../types';

export const ROLES: TargetRoleInfo[] = [
  {
    id: 'structural-design-engineer',
    name: '结构设计工程师',
    description: '负责产品内部结构方案设计，包括塑胶件、钣金件、连接方式、装配逻辑等，确保产品可制造、可装配、可量产。',
    typicalWork: [
      '完成产品3D结构建模与装配体设计',
      '输出工程图纸，配合供应商开模',
      '进行DFM/DFA分析，优化结构',
      '参与原型测试，处理试产问题',
      '与ID、电子、供应商协作推进量产',
    ],
    requiredSoftware: ['SolidWorks', 'CATIA', 'Pro/E', 'AutoCAD'],
    coreSkills: [
      'CAD三维建模',
      '工程图纸输出',
      '塑胶件/钣金件设计',
      '材料与工艺选型',
      'DFM/DFA分析',
      '公差与配合',
      '结构问题分析',
      '供应商沟通',
    ],
    commonProjects: [
      '消费电子外壳结构设计',
      '智能硬件上下壳连接方案',
      '小家电产品结构优化',
      '便携设备防水结构设计',
    ],
    portfolioRequirements: [
      '3D建模截图或爆炸图',
      '工程图或关键尺寸说明',
      '材料选择与工艺说明',
      '装配逻辑说明',
      'DFM/DFA分析记录',
      '原型测试或量产改善记录',
    ],
    resumeKeywords: ['SolidWorks', 'DFM', '塑胶件设计', '注塑', '结构方案', '工程图', '装配', '试产'],
    interviewQuestions: [
      '这个项目的结构方案是什么？为什么选择这种连接方式？',
      '这个零件如何制造？用什么材料？为什么？',
      '你有没有考虑装配顺序？如何确保可装配性？',
      '这个结构可能有哪些失效风险？',
      '如果要量产，你会如何优化这个结构？',
      '你了解注塑件的壁厚设计原则吗？',
      '卡扣结构设计时你会考虑哪些因素？',
    ],
    suitableFor: [
      '有CAD基础的机械/工业设计学生',
      '想从制造业转向消费电子的工程师',
      '希望深入结构设计的设计工程师',
    ],
    recommendedWeeks: 12,
  },
  {
    id: 'product-design-engineer',
    name: '产品设计工程师',
    description: '融合用户需求与工程实现，负责产品从概念到落地的完整设计过程，平衡造型、结构、成本和用户体验。',
    typicalWork: [
      '参与用户需求分析与产品定义',
      '主导产品概念设计与方案比较',
      '协调ID、结构、电子等多方资源',
      '推动产品从设计到量产的全流程',
      '输出产品规格书、设计说明文档',
    ],
    requiredSoftware: ['SolidWorks', 'Rhino', 'KeyShot', 'Figma', 'Adobe Suite'],
    coreSkills: [
      '用户需求分析',
      '产品概念设计',
      '结构与工艺基础',
      '跨职能协作',
      '产品管理流程',
      '原型制作与测试',
      '设计评审',
      '成本控制',
    ],
    commonProjects: [
      '消费电子新品从0到1设计',
      '智能家居产品概念到落地',
      '穿戴设备用户体验设计',
      '工业设备人机交互设计',
    ],
    portfolioRequirements: [
      '用户研究与需求分析',
      '概念方案演变过程',
      '最终设计方案展示',
      '结构可行性说明',
      '材料工艺选型',
      '原型测试与迭代',
    ],
    resumeKeywords: ['产品设计', '用户研究', '跨职能协作', '概念设计', '原型测试', 'CMF', '量产'],
    interviewQuestions: [
      '你的设计目标是什么？如何从用户需求转化为功能定义？',
      '你做过哪些方案比较？最终选择的依据是什么？',
      '如何平衡造型、结构和成本？',
      '这个项目最大的技术难点是什么？你如何解决的？',
      '你个人贡献是什么？与团队如何分工？',
    ],
    suitableFor: [
      '工业设计背景、想补强工程能力的学生',
      '有工程背景、想拓展到产品层面的工程师',
      '对全流程产品开发感兴趣的人',
    ],
    recommendedWeeks: 12,
  },
  {
    id: 'smart-hardware-engineer',
    name: '智能硬件设计工程师',
    description: '专注于智能硬件产品的整体设计，兼顾外观、结构、电子堆叠和软硬件交互，推动消费电子、IoT产品落地。',
    typicalWork: [
      '智能硬件产品结构与外观设计',
      '电子元件布局与堆叠方案',
      '天线、散热、防水结构设计',
      'PCBA与外壳的装配设计',
      '与硬件工程师协同推进量产',
    ],
    requiredSoftware: ['SolidWorks', 'CATIA', 'Rhino', 'KeyShot', 'Altium（了解）'],
    coreSkills: [
      '结构设计基础',
      '电子堆叠设计',
      '天线与散热结构',
      '防水密封设计',
      'PCB布局了解',
      'CMF设计',
      'ID与ME协作',
    ],
    commonProjects: [
      '智能音箱外壳与内部结构设计',
      '穿戴设备结构方案',
      '智能门锁硬件结构',
      '桌面IoT设备设计',
    ],
    portfolioRequirements: [
      '产品爆炸图',
      '内部堆叠说明',
      '天线/散热/防水方案',
      '外观CMF展示',
      '与PCB的装配关系',
    ],
    resumeKeywords: ['智能硬件', '电子堆叠', '防水结构', 'IoT', 'PCB装配', '天线结构', 'CMF'],
    interviewQuestions: [
      '你如何处理电子堆叠与结构空间的矛盾？',
      '这款产品的防水方案是什么？选择依据？',
      '天线布局时你会考虑哪些因素？',
      '如何协调ID和ME之间的设计冲突？',
      '你做过哪些散热结构设计？',
    ],
    suitableFor: [
      '对IoT/消费电子有兴趣的结构工程师',
      '有结构基础、想进入智能硬件赛道的工程师',
      '软硬件交叉背景的学生',
    ],
    recommendedWeeks: 16,
  },
  {
    id: 'industrial-design-engineer',
    name: '工业设计师（工程强化方向）',
    description: '在工业设计能力基础上，补强工程实现能力，能输出具有工程深度的设计方案，胜任ID与ME交叉岗位。',
    typicalWork: [
      '产品外观造型设计与CMF方案',
      '与结构工程师协作优化造型可行性',
      '输出可制造的外观设计方案',
      '参与材料、表面处理、模具方案讨论',
      '制作高保真原型验证设计',
    ],
    requiredSoftware: ['Rhino', 'SolidWorks', 'KeyShot', 'Adobe Illustrator', 'Alias（加分）'],
    coreSkills: [
      '产品造型设计',
      'CMF设计',
      '结构可行性分析',
      '材料与表面处理',
      '模型制作',
      '设计表达',
      '跨职能沟通',
    ],
    commonProjects: [
      '消费电子外观设计（含工程说明）',
      '家居产品CMF专项设计',
      '概念产品工程化方案',
    ],
    portfolioRequirements: [
      '造型演变过程',
      '最终渲染图',
      'CMF说明',
      '结构可制造性说明',
      '模型制作记录',
    ],
    resumeKeywords: ['工业设计', 'CMF', 'Rhino', 'KeyShot', '造型设计', '可制造性', '材料工艺'],
    interviewQuestions: [
      '这个造型的设计灵感和逻辑是什么？',
      '你如何确保这个外观设计在结构上可以实现？',
      '这个CMF方案的选材依据是什么？',
      '你是否考虑过这个设计的成本影响？',
    ],
    suitableFor: [
      '工业设计专业、想补强工程能力的学生',
      '纯视觉设计师、想进入产品设计赛道的人',
      '希望在ID/ME交叉岗位发展的设计师',
    ],
    recommendedWeeks: 16,
  },
  {
    id: 'mechanical-design-engineer',
    name: '机械设计工程师（产品方向）',
    description: '聚焦于机械机构设计与产品实现，掌握运动机构、传动系统和精密结构设计，应用于消费电子、机器人等领域。',
    typicalWork: [
      '机械机构分析与设计',
      '传动系统与运动仿真',
      '精密零件公差设计',
      '机构原型测试与验证',
      '工程图与BOM管理',
    ],
    requiredSoftware: ['SolidWorks（含仿真）', 'CATIA', 'AutoCAD', 'ANSYS（加分）'],
    coreSkills: [
      '机构分析与设计',
      '传动系统设计',
      '精密公差设计',
      '运动仿真',
      '有限元分析基础',
      'BOM管理',
      '工程图规范',
    ],
    commonProjects: [
      '折叠屏手机铰链机构设计',
      '机器人夹爪结构设计',
      '便携设备展开机构',
      '精密定位机构设计',
    ],
    portfolioRequirements: [
      '机构运动分析说明',
      '关键尺寸与公差',
      '仿真截图或视频',
      '原型测试记录',
      '工程图（关键件）',
    ],
    resumeKeywords: ['机械设计', '机构分析', '传动系统', '公差设计', 'SolidWorks仿真', '精密结构'],
    interviewQuestions: [
      '这个机构的运动原理是什么？',
      '如何确定关键配合尺寸的公差？',
      '你做过哪些机构优化？依据是什么？',
      '这个机构的失效模式有哪些？',
    ],
    suitableFor: [
      '机械工程背景、想进入消费电子的工程师',
      '对精密机构感兴趣的设计工程学生',
    ],
    recommendedWeeks: 12,
  },
  {
    id: 'design-engineering-intern',
    name: '设计工程实习生',
    description: '适合在校学生，快速建立工程基础知识，完成至少一个完整的工程设计项目，形成初步作品集，获得实习机会。',
    typicalWork: [
      '协助完成产品3D建模',
      '输出简单工程图',
      '参与设计评审与讨论',
      '整理项目文档与素材',
      '制作原型模型',
    ],
    requiredSoftware: ['SolidWorks 或 Rhino', 'KeyShot（加分）', 'AutoCAD基础'],
    coreSkills: [
      'CAD建模基础',
      '工程图基础',
      '材料工艺常识',
      '结构设计基础',
      '项目表达能力',
    ],
    commonProjects: [
      '桌面小产品结构设计',
      '日用品工程化改良',
      '简单外壳结构设计',
    ],
    portfolioRequirements: [
      '至少一个完整项目',
      '3D建模截图',
      '设计说明',
      '项目亮点总结',
    ],
    resumeKeywords: ['SolidWorks', '3D建模', '结构设计', '工程图', '材料工艺', '项目实践'],
    interviewQuestions: [
      '介绍一下你做的项目',
      '这个设计有什么工程考虑？',
      '你在项目中的具体贡献是什么？',
      '你对目标岗位的理解是什么？',
    ],
    suitableFor: [
      '大一至大三在校工科/设计专业学生',
      '想获取第一份设计工程实习的学生',
    ],
    recommendedWeeks: 8,
  },
];

export const PROJECT_TEMPLATES: ProjectTemplate[] = [
  {
    id: 'smart-desk-device',
    name: '智能桌面设备结构设计',
    suitableFor: ['structural-design-engineer', 'smart-hardware-engineer', 'design-engineering-intern'],
    background: '设计一款桌面智能设备（如智能音箱、桌面机器人、智能台灯），综合考虑外观造型、内部结构、电子堆叠和装配工艺。',
    targetUsers: '家庭/办公用户，追求简洁美观且功能稳定的桌面智能产品',
    designConstraints: ['整体尺寸不超过150×150×200mm', '满足基本防摔要求', '内部需容纳PCB、扬声器、电池或电源模块'],
    functionalRequirements: ['稳定放置', '方便操控（按键/触控）', '散热合理', '防尘基本保护'],
    structuralRequirements: ['上下壳连接方案', '内部支撑结构', '按键/开孔结构', '内部固定柱和卡位'],
    deliverables: ['用户需求分析', '3D结构模型截图', '爆炸图', '材料选择说明', '装配逻辑说明', 'DFM分析简述', '作品集展示页'],
    estimatedWeeks: 4,
    difficulty: 'intermediate',
  },
  {
    id: 'portable-electronics',
    name: '便携式电子产品外壳设计',
    suitableFor: ['structural-design-engineer', 'product-design-engineer', 'design-engineering-intern'],
    background: '设计一款便携式电子产品（如蓝牙耳机盒、移动电源、便携音箱）的外壳结构，重点关注结构强度、装配精度和用户手感。',
    targetUsers: '注重便携性和品质感的消费者',
    designConstraints: ['携带方便，重量轻', '跌落保护', '电池安全封装', '充电接口防护'],
    functionalRequirements: ['开合机构（如有）', '充电接口密封', '状态指示灯开孔', 'USB-C接口位置合理'],
    structuralRequirements: ['外壳连接方式', '内部固定方案', '充电模块安装', '防水防尘处理'],
    deliverables: ['概念草图', '3D模型截图', '爆炸图', '装配说明', '材料工艺选择', '作品集页面'],
    estimatedWeeks: 3,
    difficulty: 'beginner',
  },
  {
    id: 'industrial-design-to-engineering',
    name: '从工业设计概念到工程化方案',
    suitableFor: ['industrial-design-engineer', 'product-design-engineer'],
    background: '选取一个已有的工业设计概念作品，将其转化为具有工程深度的可制造方案，补充结构、材料、工艺和成本考量。',
    targetUsers: '拥有工业设计作品、需要补强工程表达的学生和设计师',
    designConstraints: ['基于已有造型方案', '需符合注塑/钣金等常规工艺', '材料成本合理'],
    functionalRequirements: ['原有功能保留', '增加工程结构说明', '材料工艺可落地'],
    structuralRequirements: ['外观件结构设计', '关键连接方式', '加工工艺说明'],
    deliverables: ['原概念展示', '工程化改良说明', '爆炸图', '材料工艺对比', '成本粗估', '作品集对比展示'],
    estimatedWeeks: 4,
    difficulty: 'intermediate',
  },
  {
    id: 'home-appliance-structure',
    name: '小家电产品结构优化',
    suitableFor: ['structural-design-engineer', 'product-design-engineer'],
    background: '对一款现有小家电产品进行结构分析和优化，提升装配效率、降低生产成本或解决已知质量问题。',
    targetUsers: '小家电制造企业，需要提升产品结构质量或降低成本',
    designConstraints: ['基于现有产品改进', '需考虑量产可行性', '不改变核心功能'],
    functionalRequirements: ['维持原产品功能', '改善装配流程', '提升结构可靠性'],
    structuralRequirements: ['现状分析', '问题识别', '优化方案', 'DFM改善'],
    deliverables: ['现状分析报告', '问题清单', '优化方案3D模型', 'DFM改善说明', '预期收益分析'],
    estimatedWeeks: 4,
    difficulty: 'intermediate',
  },
  {
    id: 'robot-gripper',
    name: '简单机器人夹爪结构设计',
    suitableFor: ['mechanical-design-engineer', 'structural-design-engineer'],
    background: '设计一款用于工业机器人或协作机器人的轻量化夹爪，考虑夹持力、重量、适用物体范围和快换接口。',
    targetUsers: '使用机器人进行装配或搬运的制造企业',
    designConstraints: ['质量不超过500g', '夹持力5-50N可调', '兼容标准机器人法兰接口'],
    functionalRequirements: ['夹持不同形状物体', '开合行程足够', '结构简单可维护'],
    structuralRequirements: ['连杆机构设计', '驱动方式选型', '关键件强度', '快换接口'],
    deliverables: ['机构运动分析', '3D装配模型', '关键件工程图', '运动仿真截图', '选材说明'],
    estimatedWeeks: 5,
    difficulty: 'advanced',
  },
  {
    id: 'elderly-assist-product',
    name: '面向老年人的辅助产品设计',
    suitableFor: ['product-design-engineer', 'industrial-design-engineer', 'design-engineering-intern'],
    background: '设计一款帮助老年人日常生活的辅助产品（如助行器附件、防跌倒报警器、智能药盒），兼顾人机工学、材料安全性和易用性。',
    targetUsers: '60岁以上老年人，手部灵活度下降，视力较弱',
    designConstraints: ['操作简单直觉', '材料安全无毒', '便于清洁', '价格亲民'],
    functionalRequirements: ['主功能稳定可靠', '操控简单（大按键/语音）', '状态反馈清晰'],
    structuralRequirements: ['人机尺寸优化', '防滑设计', '电池更换便捷', '结构耐用'],
    deliverables: ['用户调研', '人机分析', '造型方案', '结构说明', '材料安全说明', '作品集页面'],
    estimatedWeeks: 4,
    difficulty: 'beginner',
  },
];

export const getRoleById = (id: string): TargetRoleInfo | undefined =>
  ROLES.find((r) => r.id === id);

export const getProjectTemplateById = (id: string): ProjectTemplate | undefined =>
  PROJECT_TEMPLATES.find((p) => p.id === id);
